server:
  port: 8888
spring:
  application:
    name: servidor-arquivo-configuracao
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HallefBruno/spring-config-yml
          #username: username
          #password: password
          default-label: master
          search-paths:
          - 'spring-config-yml*'
