server:
  port: 8888
spring:
  application:
    name: erudio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HallefBruno/spring-config-yml
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'spring-config-yml*'
